version: '2'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    networks:
      kafka-net:
        aliases:
          - zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    networks:
      kafka-net:
        aliases:
          - kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  portainer:
    container_name: portainer-test
    restart: always
    image: portainer/portainer
    command: --templates http://templates/templates.json -d /data
    ports:
      - "7000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
